services:
  - type: web
    name: bet-scraper
    runtime: image
    repo: https://github.com/Sabatino-Cardillo/bet_scraper
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
